<a href="https://colab.research.google.com/github/CervantesMCinthiaK/Metodos-Numericos/blob/main/Eliminacion%20Gaussiana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Eliminación Gaussiana
Nombre: Cervantes Martinez Cinthia Karina

In [65]:
#Definir la biblioteca que se usara
import numpy as np

In [66]:
# Definir la matriz de coeficientes A y el vector b en listas
#Definimos la matriz de coeficientes usando  un array bidimensional de tamaño 4x4.
A = np.array([
    [1, -1, 2, -1],  # E1: 1*x1 - 1*x2 + 2*x3 - 1*x4
    [2, -2, 3, -3],  # E2: 2*x1 - 2*x2 + 3*x3 - 3*x4
    [1, 1, 1, 0],    # E3: 1*x1 + 1*x2 + 1*x3 + 0*x4
    [1, -1, 4, 3]    # E4: 1*x1 - 1*x2 + 4*x3 + 3*x4
], dtype=float) #Aqui, el sistema usted puede cambiarlo a uno de mayor o de menor tamaño.

#Y respectivamente b que son los terminos constantes de tamaño 4x1
b = np.array([-8, -20, -2, 4], dtype=float) #aqui tambien se puede cambiar los valores

In [67]:
#Realizamos el codigo que nos ayudara con los resultados
def gauss_elimination(A, b):
    n = len(A)

    # Combinamos la matriz A y el vector b en una matriz aumentada [A|b]
    Ab = np.hstack([A, b.reshape(-1, 1)])
    print("Matriz aumentada inicial [A|b]:")
    print(Ab)
    print()

    # Paso 1: Eliminacion hacia adelante
    for i in range(n - 1):
        # Paso 2: Realizamos la busqueda del pivote
        if Ab[i, i] == 0:
            print(f"Pivote cero en fila {i}, intercambiando filas...")
            # Paso 3: Intercambio de filas si el pivote es diferente de i
            for k in range(i + 1, n):
                if Ab[k, i] != 0:
                    Ab[[i, k]] = Ab[[k, i]]
                    print(f"Intercambio de filas E{i+1} y E{k+1}:")
                    print(Ab)
                    break

         # Paso 4: Realizamos la eliminacion hacia abajo para hacer ceros debajo del pivote
        for j in range(i + 1, n):
           # Paso 5: Calcular el factor de eliminacion m_ji
            m_ji = Ab[j, i] / Ab[i, i]
            # Paso 6: Actualizamos la fila j
            Ab[j, i:] -= m_ji * Ab[i, i:]
            print(f"(E{j+1} - {m_ji:.2f} * E{i+1}) → E{j+1}:")
            print(Ab)
            print()


        # Paso 7: Verificamos si tiene solución única o no.
        for row in Ab:
            if np.allclose(row[:-1], 0) and not np.isclose(row[-1], 0):
                print("Sistema inconsistente. No tiene solución.")
                return None

    # Paso 8: Sustitucion hacia atras
    x = np.zeros(n)

    # Imprimir la solución paso a paso
    print("\nSustitución hacia atrás:")

    # Paso 9: Realizamos sustitucion hacia atras para las demas incognitas
    x[-1] = Ab[-1, -1] / Ab[-1, -2]  # Última incógnita
    print(f"x4 = {x[-1]:.2f}")

    # # Paso 10: Retornamos la solucion
    for i in range(n - 2, -1, -1):
        # Para cada fila, hacer la sustitución hacia atrás
        suma = np.dot(Ab[i, i + 1:n], x[i + 1:n])  # Producto de las incógnitas ya calculadas
        x[i] = (Ab[i, -1] - suma) / Ab[i, i]  # Resolver la incógnita i

        print(f"x{i+1} = ({Ab[i, -1]:.2f} - ({suma:.2f})) / {Ab[i, i]:.2f} = {x[i]:.2f}")

    return x

# Se llama a la función para resolver el sistema
sol = gauss_elimination(A, b)

# Imprimir la solución final
if sol is not None:
    print("\nLa solución final es:")
    for i in range(len(sol)):
        print(f"x{i+1} = {sol[i]:.2f}")



Matriz aumentada inicial [A|b]:
[[  1.  -1.   2.  -1.  -8.]
 [  2.  -2.   3.  -3. -20.]
 [  1.   1.   1.   0.  -2.]
 [  1.  -1.   4.   3.   4.]]

(E2 - 2.00 * E1) → E2:
[[ 1. -1.  2. -1. -8.]
 [ 0.  0. -1. -1. -4.]
 [ 1.  1.  1.  0. -2.]
 [ 1. -1.  4.  3.  4.]]

(E3 - 1.00 * E1) → E3:
[[ 1. -1.  2. -1. -8.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  2. -1.  1.  6.]
 [ 1. -1.  4.  3.  4.]]

(E4 - 1.00 * E1) → E4:
[[ 1. -1.  2. -1. -8.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0.  2.  4. 12.]]

Pivote cero en fila 1, intercambiando filas...
Intercambio de filas E2 y E3:
[[ 1. -1.  2. -1. -8.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  2.  4. 12.]]
(E3 - 0.00 * E2) → E3:
[[ 1. -1.  2. -1. -8.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  2.  4. 12.]]

(E4 - 0.00 * E2) → E4:
[[ 1. -1.  2. -1. -8.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  2.  4. 12.]]

(E4 - -2.00 * E3) → E4:
[[ 1. -1.  2. -1. -8.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0. 

En este programa se realiza un ejercicio de un sistema de ecuaciones como matriz aumentada por eliminacion gaussiana(sustitucion hacia atras) para conocer los valores de $x_1,x_2,...x_n$ de: \\
$
E1 : x_1 − x_2 + 2x_3 − x_4 = −8\\
E2 : 2x_1 − 2x_2 + 3x_3 − 3x_4 = −20\\
E3 : x_1 + x_2 + x_3 = −2\\
E4 : x_1 − x_2 + 4x_3 + 3x_4 = 4$