<a href="https://colab.research.google.com/github/CervantesMCinthiaK/Metodos-Numericos/blob/main/Factorizacion%20LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Factorización LU
Cervantes Martinez Cinthia Karina

In [141]:
#Definiremos la biblioteca a usar
import numpy as np

In [142]:
# Definimos la matriz que deseamos factorizar (se edita si gusta otra matriz)
A = np.array([[1, 1, 0, 3],
              [2, 1, -1, 1],
              [3, -1, -1, 2],
              [-1, 2, 3, -1]], dtype=float)

b = np.array([4, 1, -3, 4], dtype=float)

In [143]:
def lu_factorization(A):
    n = A.shape[0]  # Obtiene el tamaño de la matriz A

    # Copia  la matriz original para ir modificandola
    A_copy = A.copy()

    # Inicializa L y U
    L = np.eye(n)  # Matriz L
    U = A_copy.copy()  # U es inicialmente igual a A

    print(f"Matriz inicial A:")
    print(A_copy)

    # Factorizacion LU
    for i in range(n):
        # Verificamos si el elemento diagonal de U es 0
        if U[i, i] == 0:
            raise ValueError(f"Factorizacion imposible: la matriz es singular en el paso {i+1} (U[{i}, {i}] = 0).")

        # Eliminacion para obtener U y llenar L
        for j in range(i+1, n):
            factor = U[j][i] / U[i][i]  # El factor de eliminacion
            U[j] = U[j] - factor * U[i]  # Actualizamos la fila j de U
            L[j][i] = factor  # El factor de eliminacion va a la matriz L
            print(f"(E{j+1} - {factor:.2f}E{i+1}) -> E{j+1}")
            print(U)

        # Verificamos si el elemento diagonal en U sigue siendo 0 despues de cada paso
        if U[i, i] == 0:
            raise ValueError(f"Factorización imposible: la matriz es singular después de la modificación en el paso {i+1} (U[{i}, {i}] = 0).")

    # En el final verificamos el ultimo elemento en la diagonal de U
    if U[n-1, n-1] == 0:
        raise ValueError(f"Factorizacion imposible: la matriz es singular (U[{n-1}, {n-1}] = 0).")

    print("\n Asi la matriz LU es:\n")
    print("\nMatriz L  (triangular inferior):\n")
    print(L)
    print("\nMatriz U  (triangular superior):\n")
    print(U)

    return L, U


In [144]:
#Ojo: Este paso es adicional si queremos saber el resultado del sistema usando LU
# Sustituciomos hacia adelante para resolver L * y = b
def forward_substitution(L, b):
    n = len(L)
    y = np.zeros(n)

    print("\nResolviendo L * y = b con sustitucion hacia adelante:")
    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])  # Resolviendo para y[i]
        print(f"  y[{i}] = {y[i]}")

    return y

In [145]:
# Sustitucion hacia atras para resolver U * x = y
def backward_substitution(U, y):
    n = len(U)
    x = np.zeros(n)

    print("\nResolviendo U * x = y con sustitucion hacia atras:")
    for i in range(n-1, -1, -1):  # Iteramos de abajo hacia arriba
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]  # Resolviendo para x[i]
        print(f"  x[{i}] = {x[i]}")

    return x

In [146]:
#Mandamos a imprimir
try:
    # Factorizacion LU de la matriz A
    L, U = lu_factorization(A)

    # Si la factorizacion fue exitosa, resolvemos el sistema A * x = b
    # Resolvemos el sistema L * y = b usando sustitucion hacia adelante
    y = forward_substitution(L, b)

    # Resolvemos el sistema U * x = y usando sustitucion hacia atras
    x = backward_substitution(U, y)

    print("\n Por lo tanto, la Solucion del sistema A * x = b: es")
    print(x)

except ValueError as e:
    print(e)  # Si ocurre un error de factorizacion, lo imprimimos y lo detenemos.

Matriz inicial A:
[[ 1.  1.  0.  3.]
 [ 2.  1. -1.  1.]
 [ 3. -1. -1.  2.]
 [-1.  2.  3. -1.]]
(E2 - 2.00E1) -> E2
[[ 1.  1.  0.  3.]
 [ 0. -1. -1. -5.]
 [ 3. -1. -1.  2.]
 [-1.  2.  3. -1.]]
(E3 - 3.00E1) -> E3
[[ 1.  1.  0.  3.]
 [ 0. -1. -1. -5.]
 [ 0. -4. -1. -7.]
 [-1.  2.  3. -1.]]
(E4 - -1.00E1) -> E4
[[ 1.  1.  0.  3.]
 [ 0. -1. -1. -5.]
 [ 0. -4. -1. -7.]
 [ 0.  3.  3.  2.]]
(E3 - 4.00E2) -> E3
[[ 1.  1.  0.  3.]
 [ 0. -1. -1. -5.]
 [ 0.  0.  3. 13.]
 [ 0.  3.  3.  2.]]
(E4 - -3.00E2) -> E4
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]
(E4 - 0.00E3) -> E4
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]

 Asi la matriz LU es:


Matriz L  (triangular inferior):

[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]

Matriz U  (triangular superior):

[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]

Resolviendo L * y = b co

En este ejemplo se determina la factorización LU para la matriz \( A \) en el sistema lineal \( A x = b \), donde:

\[$
A$ = \begin{bmatrix}
1 & 2 & 3 & -1 \\
2 & 1 & -1 & 3 \\
3 & -1 & -1 & 1 \\
-1 & 3 & 1 & 2
\end{bmatrix}

$b$ = \begin{bmatrix}
4 \\
1 \\
-3 \\
4
\end{bmatrix}
\]

