<a href="https://colab.research.google.com/github/CervantesMCinthiaK/Metodos-Numericos/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tutorial de Numpy
Cervantes Martinez Cinthia Karina


Numpy es una librería de Python especializada en el cálculo numérico y el análisis de datos.

Introduce una nueva clase de objetos llamada "arrays" que permite representar colecciones de datos del mismo tipo en múltiples dimensiones

In [2]:
import numpy as np #para empezar a programar se declara la libreria

In [3]:
#Si desea crear un array se utiliza
#np.array(lista) donde crea a partir de la lista o tupla proporcionada y devuelve una referencia a dicho array.

# Puedes crear un array unidimensional (vector) a partir de una lista:
a1 = np.array([-1, -2, -3, -4])
print("Array de dimension 1: ")
print(a1)

#Para crear un array bidimensional (matriz), utiliza una lista de listas:
a2 = np.array([[1.1, 2.2, 3.3], [4.4, 5.5, 6.6]])
print("Array de dimension 2: ")
print(a2)

Array de dimension 1: 
[-1 -2 -3 -4]
Array de dimension 2: 
[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]


In [4]:
#Si deseas crear un array unidimensional  con solo 2 elementos se utiliza np.empty(dimensiones):
array_vacio = np.empty(2)
print("Array vacío:\n", array_vacio) #mandamos a imprimir

#Si deseas crear un array bidimensional deberas indicar el número de filas y columnas que tendrá el array.
array_vacio = np.empty((2, 3))
print("Array vacío:\n", array_vacio)

Array vacío:
 [-5.73021895e-300  6.71880019e-310]
Array vacío:
 [[1.1 2.2 3.3]
 [4.4 5.5 6.6]]


In [5]:
#Para crear un array lleno de ceros con las dimensiones especificadas se utiliza np.zeros(dimensiones)
#Un array dimensional:
array_ceros=np.zeros(2)
print("Array de ceros:\n", array_ceros)

#por otra parte, para crear un array bidimensional se debe indicar el numero de filas y columnas
array_ceros=np.zeros((2,3))
print("Array de ceros:\n", array_ceros)

Array de ceros:
 [0. 0.]
Array de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#Si desea crear un array lleno de unos con las dimensiones especificadas se utiliza  np.ones(dimensiones):
array_unos = np.ones((2, 3)) #aqui el ejemplo es bidimensional
print("Array de unos:\n", array_unos)

Array de unos:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
#si deseas crear un array donde todos los elementos son iguales al valor proporcionado se utiliza np.full(dimensiones, valor).
array_llenado = np.full((2, 3), 7)
print("Array lleno de 7:\n", array_llenado)

Array lleno de 7:
 [[7 7 7]
 [7 7 7]]


In [8]:
#Para  un array unidimensional que contiene una secuencia de números desde inicio hasta fin, tomando valores con un paso de salto se utiliza np.arange(inicio, fin, salto).
array_rango = np.arange(0, 10, 2)
print("Array con np.arange:\n", array_rango)

Array con np.arange:
 [0 2 4 6 8]


In [9]:
#Por otra parte, existe np.linspace(inicio, fin, n) donde crea un array unidimensional con n valores equidistantes entre inicio y fin.
array_lineal = np.linspace(0, 1, 5)
print("Array con np.linspace:\n", array_lineal)

Array con np.linspace:
 [0.   0.25 0.5  0.75 1.  ]


In [10]:
#Para crear un array cuyos elementos son números aleatorios en un intervalo se utiliza  np.random.random(dimensiones):
array_aleatorio = np.random.random((2, 3)) #aqui deberas indicar el número de filas y columnas que tendrá el array
print("Array aleatorio:\n", array_aleatorio)

Array aleatorio:
 [[0.68427087 0.18418951 0.26369714]
 [0.33686729 0.65058128 0.11233712]]


#Lo interesante es que tambien Numpy cuenta con ATRIBUTOS

In [11]:
#Los atributos que usted puede utilizar son:
#a.ndim: Devuelve el número de dimensiones del array a
#a.shape: Devuelve una tupla con las dimensiones del array a
#a.size: Devuelve el número total de elementos en el array a
#a.dtype: Devuelve el tipo de datos de los elementos del array a

#Ejemplo:
# Crea un array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Imprime los atributos del array
print("Número de dimensiones:", array.ndim)
print("Dimensiones del array:", array.shape)
print("Número total de elementos:", array.size)
print("Tipo de datos de los elementos:", array.dtype)

Número de dimensiones: 2
Dimensiones del array: (2, 3)
Número total de elementos: 6
Tipo de datos de los elementos: int64


In [12]:
#Podemos añadir nuevos elementos a un array ya creado:
a = np.array((1,2,3))
np.append(a,(4,5)) #se agrega los elementos 4 y 5 al array “a”

array([1, 2, 3, 4, 5])

In [13]:
#De la misma manera podemos eliminar elementos en los arrays ya creados, para esto solamente debemos indicar la posición del elemento que queremos eliminar.
np.delete(a,1)

array([1, 3])

#Por otra parte numpy ofrece varios rangos de funciones matematicas

In [14]:
#Usted puede realizar con NumPy operaciones basicas:
a = np.array([[1, 2, 3], [4, 5, 6]]) #se crean los arrays
b = np.array([[1, 1, 1], [2, 2, 2]])
print(a + b ) #o np.add(a, b).
print(a-b) # o np.subtract(a, b)
print(a / b) # o np.divide(a, b)
print(a * b) # o np.multiply(a, b)

[[2 3 4]
 [6 7 8]]
[[0 1 2]
 [2 3 4]]
[[1.  2.  3. ]
 [2.  2.5 3. ]]
[[ 1  2  3]
 [ 8 10 12]]


In [15]:
#Ademas se puede calcular la raiz cuadrada:
# Crea los arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Divide usando np.divide(a,b)
c = np.divide(a, b)
print("División:\n", c)

# Calcula la raíz cuadrada de los elementos de c
raiz_cuadrada = np.sqrt(c)
print("Raíz cuadrada:\n", raiz_cuadrada)

División:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Raíz cuadrada:
 [[0.4472136  0.57735027]
 [0.65465367 0.70710678]]


Numpy tambien incorpora funciones para realizar las principales operaciones algebraicas con vectores y matrices.

In [16]:
#Para realizar el producto escalar de dos vectores se utiliza el operador @ o u.dot(v) donde devuelve el producto escalar de los vectores u y v
a = np.array([1, 2, 3])
b = np.array([1, 0, 1])
print(a @ b)
print(a.dot(b))

4
4


In [17]:
#Para calcular el módulo de un vector se utiliza el siguiente método: norm(v): donde devuelve el módulo del vector v.
a = np.array([3, 4]) #aqui se crea un vector Rn=R2
print(np.linalg.norm(a))

5.0


In [18]:
#Para realizar el producto matricial se crea dos arrays y se imprime usando @ o .dot
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a @ b)
print(a.dot(b))

[[14 14]
 [32 32]]
[[14 14]
 [32 32]]


In [19]:
#Para realizar el producto matricial se utiliza el mismo operador @ o a.dot(b) dond4e evuelve el producto matricial de las matrices a y b siempre y cuando sus dimensiones sean compatibles.
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a @ b)
print(a.dot(b))

[[14 14]
 [32 32]]
[[14 14]
 [32 32]]


In [20]:
#Para trasponer una matriz se utiliza el método a.T
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.T)#Devuelve la matriz traspuesta de la matriz a.

[[1 4]
 [2 5]
 [3 6]]


In [21]:
#La traza de una matriz cuadrada se calcula con el siguiente método: a.trace()
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.trace())  #Devuelve la traza (suma de la diagonal principal) de la matriz cuadrada a.

15


In [22]:
# siguiente función:det(a)
a = np.array([[1, 2], [3, 4]])
print(np.linalg.det(a)) #se calcula su determinante y lo imprime

-2.0000000000000004


In [23]:
#Si desea calcular su inversa de una matriz se calcula con la siguiente función:inv(a)
a = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [25]:
#Para resolver un sistema de ecuaciones lineales se utiliza la función siguiente:solve(a, b)
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
print(np.linalg.solve(a, b))

[-1.  1.]


In [27]:
#Pero lo mas interesante, ¿Te preguntaras como crear una tabla con numpy?
#import numpy as np mandas a llamar la funcion

# Puedes crear una tabla utilizando una lista de listas. Cada sublista representará una fila de la tabla:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Tabla inicial:\n", data)

# Despues acceder a elementos individuales utilizando índices (recordando que el índice comienza en 0)
print("Elemento en (1, 2):", data[1, 2])

# O bien acceder a una fila y una columna
print("Fila 1:", data[1, :])
print("Columna 1:", data[:, 1])

# Modificar un elemento
data[0, 0] = 10
print("Tabla modificada:\n", data)

# o realizar Funciones estadísticas
print("Media:", np.mean(data))
print("Suma de cada columna:", np.sum(data, axis=0))

Tabla inicial:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Elemento en (1, 2): 6
Fila 1: [4 5 6]
Columna 1: [2 5 8]
Tabla modificada:
 [[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]
Media: 6.0
Suma de cada columna: [21 15 18]
