<a href="https://colab.research.google.com/github/CervantesMCinthiaK/Metodos-Numericos/blob/main/Pivoteo%20Parcial%20Escaloneado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Eliminación gaussiana con pivoteo parcial escalado.
Alumna: Cervantes Martinez Cinthia Karina


In [29]:
#Definir la biblioteca  que usaremos
import numpy as np

In [30]:
# Guardamos los datos a usar:
A = [
    [2.11, -4.21,  0.921],
    [4.01,  10.2,  -1.12],
    [1.09,  0.987,  0.832]
]

b = [2.01, -3.09, 4.21]

In [38]:
#Empezamos con el Algoritmo :
def gauss_elimination_with_partial_pivoting_augmented(A, b, decimal_places=3):
    # Convertimos A y b a matrices de numpy
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)

    n = len(b)

    # Creamos la matriz aumentada [A | b]
    augmented_matrix = np.hstack((A, b.reshape(-1, 1)))

    print("Solucion:")

    # Paso 1: Inicializamos  los vectores s_i y NROW(i)
    s = np.max(np.abs(augmented_matrix[:, :-1]), axis=1)
    NROW = np.arange(n)
    # Imprimir los vectores s y la matriz aumentada
    print("Se tiene s:")
    print(np.round(s, decimal_places))
    print("")
    print("Matriz aumentada:")

    # Paso 2:Realizamos paso 3-6
    for i in range(n - 1):
        # Paso 3: Si p es el entero más pequeño con i ≤ p ≤ n y |a(NROW(p),i)|/ s(NROW(p)) = máx_i≤ j≤n|a(NROW(j),i)|/s(NROW(j))

        p = np.argmax(np.abs(augmented_matrix[i:n, i]) / s[i:n]) + i

        # Paso 4: Si es 0, el sistema no tiene solucion unica
        if augmented_matrix[p, i] == 0:
            print("No existe solucion unica.")
            return None

        # Paso 5: Intercambiar fila simulado
        if p != i:
            # Intercambio simulado de filas en la matriz aumentada
            augmented_matrix[[i, p], :] = augmented_matrix[[p, i], :]

        # Mostrar la matriz aumentada despues del posible intercambio de filas
        print("")
        print(np.round(augmented_matrix, decimal_places))
        #Paso 6 haciendo paso 7 y 8:
        for j in range(i + 1, n):
          # Paso 7: Dterminando m(NROW(j),i)
            m = augmented_matrix[j, i] / augmented_matrix[i, i]

            augmented_matrix[j, i:] -= m * augmented_matrix[i, i:]  # Paso 8: restamos el multiplo de la fila i a la fila j


            # Mostrar el valor del m
            print("")
            print(f"  m_{j+1}{i+1} = {round(m, decimal_places)}")

            # Mostrar la matriz aumentada despues de la eliminacion e intercambio
            print("")
            print(np.round(augmented_matrix, decimal_places))

    # Paso 9:Vemos si tiene solucion unica
    if augmented_matrix[n-1, n-1] == 0:
        print("No existe solucion unica.")
        return None

    # Paso 10: Hacemos x_n
    x = np.zeros(n)

    # Comenzamos por la ultima incognita
    x[n-1] = augmented_matrix[n-1, -1] / augmented_matrix[n-1, n-1]
    print(f"\n Ahora bien, sustituyendo hacia atras. \nSe tiene:\n x[{n}] = {round(x[n-1], decimal_places)}")

    # Paso 11: Realizamos la sustitucion hacia atras
    for i in range(n-2, -1, -1):
        # Calculamos x[i]
        sum_product = np.dot(augmented_matrix[i, i+1:n], x[i+1:n])  # Calculamos la suma de los productos
        x[i] = (augmented_matrix[i, -1] - sum_product) / augmented_matrix[i, i]

        # Imprimimos como se calcula x[i]
        print("")
        print(f"  x[{i+1}] = ({round(augmented_matrix[i, -1], decimal_places)} - "
              f"{round(sum_product, decimal_places)}) / {round(augmented_matrix[i, i], decimal_places)}")

        # Mostrar el valor de x[i]
        print(f"  x[{i+1}] = {round(x[i], decimal_places)}")

    # Paso 12: Retornar la solucion
    print("\nPor lo tanto, La solucion final es:")
    for i in range(n):
        print(f"x{i+1} = {round(x[i], decimal_places)}")

    return x

# Resolvemos el sistema Ax = b utilizando la matriz aumentada
solution = gauss_elimination_with_partial_pivoting_augmented(A, b)



Solucion:
Se tiene s:
[ 4.21 10.2   1.09]

Matriz aumentada:

[[ 1.09   0.987  0.832  4.21 ]
 [ 4.01  10.2   -1.12  -3.09 ]
 [ 2.11  -4.21   0.921  2.01 ]]

  m_21 = 3.679

[[  1.09    0.987   0.832   4.21 ]
 [  0.      6.569  -4.181 -18.578]
 [  2.11   -4.21    0.921   2.01 ]]

  m_31 = 1.936

[[  1.09    0.987   0.832   4.21 ]
 [  0.      6.569  -4.181 -18.578]
 [  0.     -6.121  -0.69   -6.14 ]]

[[  1.09    0.987   0.832   4.21 ]
 [  0.     -6.121  -0.69   -6.14 ]
 [  0.      6.569  -4.181 -18.578]]

  m_32 = -1.073

[[  1.09    0.987   0.832   4.21 ]
 [  0.     -6.121  -0.69   -6.14 ]
 [  0.      0.     -4.921 -25.168]]

 Ahora bien, sustituyendo hacia atras. 
Se tiene:
 x[3] = 5.114

  x[2] = (-6.14 - -3.527) / -6.121
  x[2] = 0.427

  x[1] = (4.21 - 4.677) / 1.09
  x[1] = -0.428

Por lo tanto, La solucion final es:
x1 = -0.428
x2 = 0.427
x3 = 5.114


  Eliminación gaussiana con pivoteo parcial escalado \\
  En este programa se implementa el sistema lineal con aritmética de redondeo de tres dígitos. \\
$2.11x_1- 4.21x_2+0.921x_3= 2.01,\\
 4.01x_1+ 10.2x_2- 1.12x_3=-3.09,\\
 1.09x_1+0.987x_2+0.832x_3= 4.21.$